//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public string CommentText { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CommentAuthor { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
